// Code generated by MockGen. DO NOT EDIT.
// Source: ctl/project/backend.go

// Package project_test is a generated GoMock package.
package project_test

import (
	context "context"
	container "github.com/foldsh/fold/ctl/container"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockBackend is a mock of Backend interface
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
}

// MockBackendMockRecorder is the mock recorder for MockBackend
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Context mocks base method
func (m *MockBackend) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockBackendMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockBackend)(nil).Context))
}

// NewNetwork mocks base method
func (m *MockBackend) NewNetwork(name string) *container.Network {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewNetwork", name)
	ret0, _ := ret[0].(*container.Network)
	return ret0
}

// NewNetwork indicates an expected call of NewNetwork
func (mr *MockBackendMockRecorder) NewNetwork(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewNetwork", reflect.TypeOf((*MockBackend)(nil).NewNetwork), name)
}

// CreateNetworkIfNotExists mocks base method
func (m *MockBackend) CreateNetworkIfNotExists(net *container.Network) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetworkIfNotExists", net)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNetworkIfNotExists indicates an expected call of CreateNetworkIfNotExists
func (mr *MockBackendMockRecorder) CreateNetworkIfNotExists(net interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetworkIfNotExists", reflect.TypeOf((*MockBackend)(nil).CreateNetworkIfNotExists), net)
}

// RemoveNetworkIfExists mocks base method
func (m *MockBackend) RemoveNetworkIfExists(net *container.Network) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNetworkIfExists", net)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNetworkIfExists indicates an expected call of RemoveNetworkIfExists
func (mr *MockBackendMockRecorder) RemoveNetworkIfExists(net interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNetworkIfExists", reflect.TypeOf((*MockBackend)(nil).RemoveNetworkIfExists), net)
}

// NewContainer mocks base method
func (m *MockBackend) NewContainer(name string, image container.Image, mounts ...container.Mount) *container.Container {
	m.ctrl.T.Helper()
	varargs := []interface{}{name, image}
	for _, a := range mounts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewContainer", varargs...)
	ret0, _ := ret[0].(*container.Container)
	return ret0
}

// NewContainer indicates an expected call of NewContainer
func (mr *MockBackendMockRecorder) NewContainer(name, image interface{}, mounts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name, image}, mounts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewContainer", reflect.TypeOf((*MockBackend)(nil).NewContainer), varargs...)
}

// GetContainer mocks base method
func (m *MockBackend) GetContainer(name string) (*container.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainer", name)
	ret0, _ := ret[0].(*container.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainer indicates an expected call of GetContainer
func (mr *MockBackendMockRecorder) GetContainer(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainer", reflect.TypeOf((*MockBackend)(nil).GetContainer), name)
}

// RunContainer mocks base method
func (m *MockBackend) RunContainer(con *container.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunContainer", con)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunContainer indicates an expected call of RunContainer
func (mr *MockBackendMockRecorder) RunContainer(con interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunContainer", reflect.TypeOf((*MockBackend)(nil).RunContainer), con)
}

// StopContainer mocks base method
func (m *MockBackend) StopContainer(con *container.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopContainer", con)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopContainer indicates an expected call of StopContainer
func (mr *MockBackendMockRecorder) StopContainer(con interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopContainer", reflect.TypeOf((*MockBackend)(nil).StopContainer), con)
}

// RemoveContainer mocks base method
func (m *MockBackend) RemoveContainer(con *container.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContainer", con)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContainer indicates an expected call of RemoveContainer
func (mr *MockBackendMockRecorder) RemoveContainer(con interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainer", reflect.TypeOf((*MockBackend)(nil).RemoveContainer), con)
}

// AddToNetwork mocks base method
func (m *MockBackend) AddToNetwork(n *container.Network, con *container.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToNetwork", n, con)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToNetwork indicates an expected call of AddToNetwork
func (mr *MockBackendMockRecorder) AddToNetwork(n, con interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToNetwork", reflect.TypeOf((*MockBackend)(nil).AddToNetwork), n, con)
}
